"""add Reserve

Revision ID: 082218873ef9
Revises: 5015d2cbb44d
Create Date: 2024-09-01 14:40:47.321872

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '082218873ef9'
down_revision: Union[str, None] = '5015d2cbb44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reserves',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'product_id', name='_user_product_uc')
    )
    op.create_index(op.f('ix_reserves_id'), 'reserves', ['id'], unique=False)
    op.drop_column('products', 'reserved_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products',
                  sa.Column('reserved_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False,
                            nullable=False))
    op.drop_index(op.f('ix_reserves_id'), table_name='reserves')
    op.drop_table('reserves')
    # ### end Alembic commands ###
