services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

    ports:
      - ${DB_PORT}:${DB_PORT}


volumes:
  db:
